### ISSUE TITLE
ekz can't create cluster on Windows 10.

### ISSUE THREAD

**Issue by udomsak** [chanwit/ekz#82]
# Details

## Error
cmd: ``` ekz create cluster```

output: 
```
✔ the default provider is: ekz
► pulling image: quay.io/ekz-io/ekz:v1.19.8-eks-1-19-4.4 ...
✗ error pulling image: quay.io/ekz-io/ekz:v1.19.8-eks-1-19-4.4: command "docker": exit status 1
```
cmd: ``` ekz create cluster --provider=kind```
output:
 ```
✔ the default provider is: kind
► pulling image quay.io/ekz-io/kind:v1.19.8-eks-1-19-4.0 ...
✗ command "docker": exit status 1

```
## Root cause. 
**don't know**

### EKZ version.
**0.4.1** 
### Operating System.
Edition: **Windows 10 pro**
Version: 20H2
OSBuild: **19042.928**
Experience: Windows Feature Experience Pack 120.2212.551.0

### Docker 
pathDockerBin: C:\ProgramData\DockerDesktop\version-bin\docker.exe
dockerVersion: ```Docker version 20.10.2, build 2291f61```

**Comment by chanwit** [comment]
I closed this issue as Windows people reported back to me that it's working fine there, both on Power Shell and WSL2.
